layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

topics:
  - name: Java
    web_url: https://github.com/lucianojung?tab=repositories
    image_url: https://cdn.pixabay.com/photo/2017/05/19/21/12/java-2327538_960_720.png

  - name: Game Dev
    web_url: https://github.com/lTimeless/BrackeyGameJam-2
    image_url: https://github.com/lTimeless/BrackeyGameJam-2/blob/master/Assets/BackgroundScenes/AttackingWithKnife/AtackingWithKnife%20(1).png

  - name: Android
    image_url: https://upload.wikimedia.org/wikipedia/commons/6/66/Android_robot.png
    
  - name: Elektronik
